name: backend-deploy

on:
    push:
        branches:
            - master
        paths:
            - 'backend/**'
    
jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy backend
        steps:
            - uses: actions/checkout@v1
            - uses: actions-hub/gcloud@master
              env:
                  PROJECT_ID: gifted-antonym-271008
                  APPLICATION_CREDENTIALS: ${{secrets.GAE_SA_KEY}}
              with:
                  args: app deploy ./backend/app.yaml
