# This is a basic workflow to help you get started with Actions

name: frontend-build-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    paths:
        - 'frontend/'
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Use node
          uses: actions/setup-node@v1
          with:
              node-version: '12.x'
        - run: yarn install
