# This is a basic workflow to help you get started with Actions

name: frontend-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
            - master
        paths:
            - 'frontend/**'
    
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
        - uses: actions/checkout@v2
        - name: Use node
          uses: actions/setup-node@v1
          with:
              node-version: '12.x'
        - run: yarn install
          working-directory: ./frontend
    deploy:
        needs: build
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: deploy firebase
              working-directory: ./frontend
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
