name: frontend-build-and-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
            - master
        paths:
            - 'frontend/**'
    
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        name: Build
        steps:
        - uses: actions/checkout@v2
        - name: Use node
          uses: actions/setup-node@v1
          with:
              node-version: '12.x'
        - run: yarn install
          working-directory: ./frontend
        - run: yarn build
          working-directory: ./frontend
        - name: deploy firebase
          uses: w9jds/firebase-action@master
          with:
              args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  PROJECT_PATH: ./frontend
